# Dependencies
markdown:	kramdown
highlighter:	rouge

# Permalinks
permalink:	/blog/:title

# Setup
title:		'Souhail HANFI'
tagline:	'blog'
description:	'My personal blog.'
url:		https://hanfi.github.io/
author:
  name:		'Souhail Hanfi'
  url:		https://twitter.com/VenOmaX666

paginate:	5

#comments
comments: google

#share
share: yes

#analytics
googleAnalyticsID: UA-105982304-1

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/souhail-hanfi
    desc:	Find me on LinkedIn

  - icon:	github
    url:	https://github.com/hanfi
    desc:	Fork me on github

  - icon:	twitter
    url:	https://twitter.com/VenOmaX666
    desc:	Follow me on twitter

  - icon:	facebook
    url:	https://www.facebook.com/souhail.hanfi
    desc:	Follow me on facebook

  - icon:	image
    url:	https://500px.com/souhailhanfi
    desc:	Follow me on 500px

  - icon:	feed
    url:	https://hanfi.github.io/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

plugins:
  - jekyll-paginate

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'bitbucket-pipelines.yml', 'script', 'vendor']

copyright:
  author:	SOUHAIL HANFI
  url:		https://hanfi.github.io/
  type_title:	Some rights reserved
  type_url:	https://creativecommons.org/licenses/by-nc/2.5
