# Dependencies
markdown:	redcarpet
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		'Souhail HANFI'
tagline:	'blog'
description:	'My personal blog.'
url:		http://hanfi.github.io/
author:
  name:		'Souhail Hanfi'
  url:		https://twitter.com/VenOmaX666

paginate:	5

#comments
comments: facebook

#share
share: yes

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/VenOmaX666
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/hanfi
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/+SouhailHanfi?rel=author
    desc:	Add me on google+

  - icon:	feed
    url:	http://hanfi.github.io/atom.xml
    desc:	Subscribe to my feed

menu:
  - title:	Home
    url:	/

  - title:	About
    url:	/about

copyright:
  author:	SOUHAIL HANFI
  url:		http://hanfi.github.io/
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
