image: ruby

pipelines:
    default:
      - step:
          caches:
            - bundler
          script:
            - gem install jekyll
            - bundle install
            - git clone --branch="master" --depth 1 https://hanfi:$GIT_PASSWORD@bitbucket.org/hanfi/hanfi.bitbucket.io.git _site
            - jekyll build
            - cd _site
            - git add . && git -c user.name='hanfi' -c user.email='souhail.hanfi@gmail.com' commit -m "$BITBUCKET_COMMIT"
            - git push origin master

definitions:
  caches:
    bundler: vendor/bundle
